import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const dir = "build/hevy";

const copyRequiredFiles = () => {
    try {
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
        fs.copyFileSync("styles.css", path.join(dir, "styles.css"));
        fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
        console.log(`✓ Files copied to ${dir}`);
    } catch (err) {
        console.error("Failed to copy files:", err.message);
    }
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: path.join(dir, "main.js"),
});

if (prod) {
    await context.rebuild();
    copyRequiredFiles();
    process.exit(0);
} else {
    await context.watch();
    copyRequiredFiles();
}